version: '3.8'

services:
  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Ensure you have a Dockerfile in your Java project directory
    ports:
      - "8080:8080"  # Expose port 8080 for the Java application
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - db  # Ensure the database service starts before the app

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=mydatabase  # Set the name of the default database
      - MYSQL_ROOT_PASSWORD=rootpassword  # Set the MySQL root password
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"  # Expose the MySQL port
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql-data:  # Define a volume for MySQL data persistence
