version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-javafx-app
    environment:
      DISPLAY: host.docker.internal:0.0
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db_data:
